# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rnkCalc <- function(logrhonk, lse, N, K) {
    .Call(`_VICatMix_rnkCalc`, logrhonk, lse, N, K)
}

.ElogphiCalc <- function(eps, K, D, N, maxNCat, X) {
    .Call(`_VICatMix_ElogphiCalc`, eps, K, D, N, maxNCat, X)
}

.ElogphiLCalc <- function(eps, K, D, maxNCat) {
    .Call(`_VICatMix_ElogphiLCalc`, eps, K, D, maxNCat)
}

.logrhonkCalc <- function(Elogpi, Elogphi, K, D, N) {
    .Call(`_VICatMix_logrhonkCalc`, Elogpi, Elogphi, K, D, N)
}

.epsCalc <- function(K, maxNCat, D, N, prioreps, X, rnk) {
    .Call(`_VICatMix_epsCalc`, K, maxNCat, D, N, prioreps, X, rnk)
}

.firstepsCalc <- function(K, maxNCat, D, N, prioreps, X, clusterInit) {
    .Call(`_VICatMix_firstepsCalc`, K, maxNCat, D, N, prioreps, X, clusterInit)
}

.CpriorepsCalc <- function(prioreps, K, D, maxNCat) {
    .Call(`_VICatMix_CpriorepsCalc`, prioreps, K, D, maxNCat)
}

.CpostepsCalc <- function(eps, K, D, maxNCat) {
    .Call(`_VICatMix_CpostepsCalc`, eps, K, D, maxNCat)
}

.sumDElogphiCalc <- function(Elogphi, K, D, N) {
    .Call(`_VICatMix_sumDElogphiCalc`, Elogphi, K, D, N)
}

.priorepsminusoneCalc <- function(prioreps, K, D, maxNCat) {
    .Call(`_VICatMix_priorepsminusoneCalc`, prioreps, K, D, maxNCat)
}

.epsminusoneCalc <- function(eps, K, D, maxNCat) {
    .Call(`_VICatMix_epsminusoneCalc`, eps, K, D, maxNCat)
}

.epsminuspriorepsCalc <- function(eps, prioreps, K, D, maxNCat) {
    .Call(`_VICatMix_epsminuspriorepsCalc`, eps, prioreps, K, D, maxNCat)
}

.ElogthetaCalcCat <- function(beta, K, J) {
    .Call(`_VICatMix_ElogthetaCalcCat`, beta, K, J)
}

.cmatrixCalc <- function(nullphi, X, c, N, D) {
    .Call(`_VICatMix_cmatrixCalc`, nullphi, X, c, N, D)
}

.betaCalc <- function(priorbeta, y, K, J, N, rnk) {
    .Call(`_VICatMix_betaCalc`, priorbeta, y, K, J, N, rnk)
}

.CpriorbetaCalc <- function(priorbeta, K, J) {
    .Call(`_VICatMix_CpriorbetaCalc`, priorbeta, K, J)
}

.CpostbetaCalc <- function(beta, K, J) {
    .Call(`_VICatMix_CpostbetaCalc`, beta, K, J)
}

.respthetaCalc <- function(Elogtheta, rnk, y, N, K) {
    .Call(`_VICatMix_respthetaCalc`, Elogtheta, rnk, y, N, K)
}

.nullphiCalc <- function(X, nCat, maxNCat, D, N) {
    .Call(`_VICatMix_nullphiCalc`, X, nCat, maxNCat, D, N)
}

.firstbetaCalc <- function(y, priorbeta, K, J, N, clusterInit) {
    .Call(`_VICatMix_firstbetaCalc`, y, priorbeta, K, J, N, clusterInit)
}

.lognullphiCalc <- function(nullphi, X, K, D, N) {
    .Call(`_VICatMix_lognullphiCalc`, nullphi, X, K, D, N)
}

.logrhonkCalcVarSel <- function(Elogpi, carray, cmatrix, K, D, N) {
    .Call(`_VICatMix_logrhonkCalcVarSel`, Elogpi, carray, cmatrix, K, D, N)
}

.epsCalcVarSel <- function(K, maxNCat, D, N, prioreps, X, rnk, c) {
    .Call(`_VICatMix_epsCalcVarSel`, K, maxNCat, D, N, prioreps, X, rnk, c)
}

.CpostdeltaCalc <- function(c, a, D) {
    .Call(`_VICatMix_CpostdeltaCalc`, c, a, D)
}

.logeta1Calc <- function(Elogphi, rnk, Elogdelta, K, D, N) {
    .Call(`_VICatMix_logeta1Calc`, Elogphi, rnk, Elogdelta, K, D, N)
}

.logeta2Calc <- function(lognullphi, rnk, Elogminusdelta, K, D, N) {
    .Call(`_VICatMix_logeta2Calc`, lognullphi, rnk, Elogminusdelta, K, D, N)
}

.cCalc <- function(logeta1, clse, D) {
    .Call(`_VICatMix_cCalc`, logeta1, clse, D)
}

.sumDElogphiCalcVarSel <- function(carray, cmatrix, K, D, N) {
    .Call(`_VICatMix_sumDElogphiCalcVarSel`, carray, cmatrix, K, D, N)
}

.logrhonkCalcProfCat <- function(Elogpi, Elogtheta, y, carray, cmatrix, K, D, N) {
    .Call(`_VICatMix_logrhonkCalcProfCat`, Elogpi, Elogtheta, y, carray, cmatrix, K, D, N)
}

